const COLLEGES_LIST = [{key:'1', label:'University Departments of Anna University, Chennai - CEG Campus, Sardar Patel Road, Guindy, Chennai 600 025'},
    {key:'2', label:'University Departments of Anna University, Chennai - ACT Campus, Sardar Patel Road, Guindy, Chennai 600 025'},
    
    {key: '3', label: 'University Departments of Anna University, Chennai - SAP Campus, Sardar Patel Road, Guindy, Chennai 600 025' },

    {key:'4', label:'University Departments of Anna University, Chennai - MIT Campus, Chrompet, Tambaram Taluk, Kancheepuram District 600 044'},
    {key:'5', label:'Annamalai University Faculty of Engineering and Technology,Annamalai nagar,Cuddalore 608002'},
    {key:'1013', label:'University College of Engineering, Villupuram, Kakuppam, Villupuram District 605103'},
    {key:'1014', label:'University College of Engineering, Tindivanam, Melpakkam, Tindivanam, Villupuram District 604001'},
    {key:'1015', label:'University College of Engineering, Arni, Arni to Devikapuram Road, Thatchur, Arni, Thiruvannamalai District 632326'},
    {key:'1026', label:'University College of Engineering, Kancheepuram, Ponnerikarai Campus, NH4, Chennai-Bangalore Highway, Karaipettai Village & Post, Kancheepuram District 631552'},
    {key:'1101', label:'Aalim Muhammed Salegh College of Engineering, Muthapudupet, Avadi IAF, Chennai 600055'},
    {key:'1106', label:'Jaya Engineering College, Thirunindravur, Chennai 602024'},
    {key:'1107', label:'Jaya Institute of Technology, Kanchipadi Post, Thiruvallur-Tiruttani NH  Road, Thiruvallur District 631204'},
    {key:'1110', label:'Prathyusha Engineering college, Aranvoyalkuppam, Thiruvallur District 602025'},
    {key:'1112', label:'R M D Engineering College, Kavaraipettai, Gummidipoondi, Thiruvallur District 601206'},
    {key:'1113', label:'R M K Engineering College, Kavaraipettai, Gummidipoondi, Thiruvallur District 601206'},
    {key:'1114', label:'S A Engineering College, Thiruverkadu, Chennai  Thiruvallur District 600077'},
    {key:'1115', label:'Sri Ram Engineering College, Perumalpattu, Veppampattu (R S), Thiruvallur District 602 024'},
    {key:'1116', label:'Sri Venkateswara College of Engineering and Technology, Thirupachur, Thiruvallur District 631203'},
    {key:'1118', label:'Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous), Avadi-Alamathi Road, Chennai 600 062'},
    {key:'1120', label:'Velammal Engineering College (Autonomous), Ambattur-Redhills Road, Chennai 600066'},
    {key:'1121', label:'Sri Venkateswara Institute of Science and Technology, Kozhundalur, Thiruvallur District 631203'},
    {key:'1122', label:'Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College, Avadi-Alamathi Road, Chennai 600 062'},
    {key:'1123', label:'Gojan School of Business and Technology, Alamathi, Chennai 600062'},
    {key:'1124', label:'SAMS College of Engineering and Technology, Panappakkam, Chennai-Tirupathi Road, Uthukkottai Taluk, Thiruvallur District 601102'},
    {key:'1125', label:'P M R Engineering College, Adayalampattu, Maduravoyal , Vanagaram, Chennai 600095'},
    {key:'1126', label:'J N N Institute of Engineering, Ushaa Garden, Kannigaipair Village, Uthukottai Taluk, Thiruvallur District 601102'},
    {key:'1127', label:'St. Peters College of Engineering and Technology, College Road, Avadi, Chennai 600 054'},
    {key:'1128', label:'R M K College of Engineering and Technology, Puduvoyal, Gummidipoondi Taluk, Thiruvallur District 601206'},

    {key: '1129', label: 'Jaya School of Architecture, Poonamallee Bypass, Poonamallee, Thiruvallur District 600056' },
    {key: '1130', label: 'MARG Instiute of Design & Architecture Swarnabhoomi (MIDAS), Marg Swarnabhoomi, Velur Village, Cheyyur Post, Kancheepuram District 603302' },

    {key:'1131', label:'Vel Tech, Avadi-Alamathi Road, Chennai 600062'},

    {key: '1132', label: 'Rajalakshmi School of Architecture, Thandalam, Sriperumpudur Taluk, Kancheepuram District 602105' },

    {key:'1133', label:'Annai Veilankannis College of Engineering, Gandhi Road, Nedungundram, Chennai 600048'},
    
    {key: '1134', label: 'Surya School of Architecture, GST Road, Vikravandi Village, Villupuram District 605652' },
    {key: '1135', label: 'Aalim Muhammed Salegh Academy of Architecture, Muthapudupet, Avadi IAF, Chennai 600055' },

    {key:'1137', label:'Annai Mira College of Engineering and Technology, Arcot Road, Arappakkam Village, Walaja Taulk, Vellore District 632 517'},

    {key: '1138', label: 'Davinci School of Design and Architecture, Karapakkam, Chennai 600097' },

    {key:'1140', label:'Jeppiaar Institute Of Technology, Kunnam Village, Sriperumpudur Taluk, Kancheepuram District 631604'},
    {key:'1141', label:'R V S Padmavathy College of Engineering and Technology, Senthil Pakkam Village, Roshanagaram  Post, Madarapakkam Via, Gummidipoondi Taluk, Thiruvallur District 601202'},
    {key:'1143', label:'Kumaran Institute of Techonology, Kollati Village, Minjur, Ponneri Taluk, Thiruvallur District 601203'},

    {key: '1144', label: 'R V S Padmavathy School of Architecture, Senthil Pakkam Village, Roshanagaram Post, Madarapakkam Via, Gummidipoondi Taluk, Thiruvallur District 601202' },
    {key: '1145', label:'Anand School of Architecture, Old Mahalibalipuram Road (OMR), Kazhipattur, Kancheepuram District 603103' },
    {key: '1146', label: 'Misrimal Navajee Munoth Jain School of Architecture, Rajiv Gandhi Salai (OMR), Thoraipakkam, Chennai 600096' },
    {key: '1147', label: 'MMES ACADEMY OF ARCHITECTURE, VELLORE' },

    {key:'1149', label:'St. Josephs Institute of Technology, Jeppiaar Nagar, Old Mahabalipuram Road (OMR), Chennai 600119'},
    {key:'1150', label:'Sri Jayaram Institute of Engineering and Technology, 51 N, Elavur, 58N, Natham, Gummidipoondi Taluk, Thiruvallur District 601201'},

    {key: '1152', label: 'CAAD - Chennai Academy of Architecture and Design, No.24, Thumbakkam, Chennai-Thirupathi Highway, Near Periyapalayam Amman Temple, Chennai 601102' },
    {key: '1153', label: 'Jawahar School of Architecture Planning and Design, No.54, K K Road, Saligramam, Chennai 600093' },

    {key:'1201', label:'Arignar Anna Institute of Science and Technology, Pennalur, Sriperumpudur, Taluk, Kancheepuram District 602105'},
    {key:'1202', label:'D M I College of Engineering, Palanchoor, Nazrethpet, Chennai 602103'},
    {key:'1205', label:'Lord Venkateshwara Engineering College, Walajabad Post, Kancheepuram District 631605'},
    {key:'1206', label:'Jeppiaar Maamallan Engineering College, Vadamangalam Post, Kancheepuram District 602105'},
    {key:'1207', label:'Kings Engineering College, Sriperumpudur Taluk, Kancheepuram District 602105'},
    {key:'1209', label:'Pallavan College of Engineering, Thimmasamudram, Kancheepuram District 631502'},
    {key:'1210', label:'Panimalar Engineering College, Nazarethpet, Poonamallee, Chennai 602103'},
    {key:'1211', label:'Rajalakshmi Engineering College (Autonomous), Thandalam, Sriperumpudur Taluk, Kancheepuram District 602105'},
    {key:'1212', label:'Rajiv Gandhi College of Engineering, Nemili, Sriperumpudur Taluk, Kancheepuram District 602105'},
    {key:'1213', label:'S K R Engineering College, Poonamallee, Chennai 600123'},
    {key:'1214', label:'Sakthi Mariamman Engineering College, Narayanasamy Nagar, Thandalam, Chennai 602105'},
    {key:'1216', label:'Saveetha Engineering College (Autonomous), Thandalam, Sriperumpudur Taluk, Kancheepuram District 602105'},
    {key:'1217', label:'Sree Sastha Institute of Engineering and Technology, Chembarambakkam, Chennai 600123'},
    {key:'1218', label:'Sri Muthukumaran Institute of Technology, Near Mangadu, Chennai 600069'},
    {key:'1219', label:'Sri Venkateswara College of Engineering (Autonomous), Post Bag No.1, Chennai-Bengaluru High Road, Pennalur, Irungattukottai S.O., Sriperumbudur Taluk, Kancheepuram District 602117'},
    {key:'1221', label:'Jaya College of Engineering and Technology, Parivakkam, Poonamallee, Chennai 600056'},
    {key:'1222', label:'P B College of Engineering, Irungkattukottai, Sriperumpudur Taluk, Kancheepuram District 602105'},
    {key:'1225', label:'Loyola Institute of Technology, Mevaloorkuppam, B Village, Palanchoor, Nazarethpet Post, Chennai 600123'},
    {key:'1226', label:'P T Lee Chengalvaraya Naicker College of Engineering and Technology, Oovery, Veliyur Post, Kancheepuram District 631 502'},
    {key:'1228', label:'Alpha College of Engineering, Dr. Grace George Nagar, Udayavar Koil Street, Thirumazhisai, Poonamalle, Chennai 602107'},
    {key:'1229', label:'Indira Institute of Engineering and Technology, VGR Gardens, Pandur, Thiruvallur District 631203'},
    {key:'1230', label:'Apollo Engineering College, Mevaloorkuppam, Valarpuram Post, Sriperumpudur, Kancheepuram District 602105'},
    {key:'1231', label:'Panimalar Institute of Technology, Nazarethpet, Poonamallee, Chennai 602103'},
    {key:'1232', label:'A R M College of Engineering and Technology, Sattamangalam, Maraimalainagar, Chengalpattu District 603209'},
    {key:'1233', label:'Adhi College of Engineering and Technology, Pazhayaseevaram, Madura Sankarapuram Village, Kancheepuram District 631605'},
    {key:'1234', label:'Indira Gandhi College of Engineering and Technology for Women,  Chengalpattu-Kancheepuram High Road, Chengalpattu District 603101'},
    {key:'1235', label:'JEI Mathaajee College of Engineering, Vishakandikupam Village, Kancheepuram District 631552'},
    {key:'1237', label:'Velammal Institute of Technology, Chennai-Kolkatta Highway, Panchetti Village, Ponneri Taluk, Thiruvallur District 601204'},
    {key:'1238', label:'GRT Institute of Engineering and Technology, GRT Mahalakshmi Nagar, Chennai-Tirupathi Highway, Tiruttani Taluk, Thiruvallur District 631209'},
    {key:'1241', label:'T J S Engineering College, Peruvoyal, Near Kavaraipettai, Gummidipoondi Taluk, Thiruvallur District 601206'},
    {key:'1243', label:'Madha Institute of Engineering and Technology, Erandamkattalai Village, Sadhananthapuram, Thandalam Post, Chennai  602101'},
    {key:'1301', label:'Mohamed Sathak A J College of Engineering, Old Mahabalipuram Road (OMR), Egattur, Chengalpattu District 603103'},
    {key:'1303', label:'Anand Institute of Higher Technology, Old Mahabalipuram Road (OMR), Kazhipattur, Chengalpattu District  603103'},
    {key:'1304', label:'Easwari Engineering College (Autonomous), Ramapuram, Chennai 600089'},
    {key:'1306', label:'Jeppiar Engineering College, Old Mahabalipuram Road (OMR), Chennai 600119'},
    {key:'1307', label:'Jerusalem College of Engineering (Autonomous), Narayanapuram, Pallikaranai, Chennai 600 100'},

    {key: '1308', label: 'Measi Academy of Architecture, Royapettah, Chennai 600014'},

    {key:'1309', label:'Meenakshi Sundararajan Engineering College, Kodambakkam, Chennai 600024'},
    {key:'1310', label:'Misrimal Navajee Munoth Jain Engineering College, Rajiv Gandhi Salai (OMR), Thorappakkam, Chennai 600096'},
    {key:'1311', label:'K C G College of Technology, Karappakkam, Chennai 600096'},
    {key:'1313', label:'SMK  Fomra Institute of Technology,Fomra Nagar, OMR,(IT Express Highway),Kelambakkam,Chennai- 603103'},
    {key:'1315', label:'Sri Sivasubramaniya Nadar College of Engineering (Autonomous), Kalavakkam, Old Mahabalipuram Road (OMR), Chengalpattu District 603110'},
    {key:'1316', label:'Agni College of Technology, Old Mahabalipuram Road (OMR), Thalambur Village, Chengalpattu District 603103'},
    {key:'1317', label:'St. Joseph’s College of Engineering, Old Mahabalipuram Road (OMR), Chennai 600 119'},
    {key:'1319', label:'Thangavelu Engineering College, Karappakkam, Chennai 600097'},
    {key:'1320', label:'Jeppiaar SRR Engineering College, Old Mahabalipuram Road, Chengalpattu District 603103'},
    {key:'1321', label:'Central Institute of Plastics Engineering and Technology (CIPET), Guindy, Chennai 600032'},
    {key:'1322', label:'Dhanalakshmi Srinivasan College of Engineering and Technology, East Coast Road, Poonjeri, Chennai 603104'},
    {key:'1323', label:'A C T College of Engineering and Technology, Nelvoy Village, Pukkathurai Post, Maduranthagam, Chengalpattu District 603107'},
    {key:'1324', label:'Sri Sai Ram Institute of Technology, West Tambaram, Chennai 600044'},
    {key:'1325', label:'St. Joseph College of Engineering, Trinity Campus, Nemili, Sriperumpudur Taluk, Kancheepuram District 602105'},
    {key:'1333', label:'Vi Institute of Technology, Sirunkundram Village & Post, Chengalput Taluk, Chengalpattu District 603108'},
    {key:'1334', label:'ARS College of Engineering, Maraimalai Nagar Post, Chengalpattu District 603209'},
    {key:'1335', label:'Sri Krishna Institute of Technology, Panapakkam, Padappai,  Chennai 601301'},
    {key:'1399', label:'Chennai Institute of Technology, Puduper Village, Nandambakkam Post, Kundrathur, Chennai 600069'},

    {key: '1400', label: 'Mohamed Sathak A J Academy of Architecture, Old Mahabalipuram Road (OMR), Kancheepuram District 603103' },


    {key:'1401', label:'Adhiparasakthi Engineering College, Melmaruvathur, Chengalpattu District 603319'},
    {key:'1402', label:'Annai Terasa College of Engineering, Thirunavalur, Kallakurichi District 607204'},
    {key:'1405', label:'Dhanalakshmi College of  Engineering, Manimangalam, Chennai 601301'},
    {key:'1406', label:'Dr. Pauls Engineering College, Pauls Nagar, Pulichapallam Village, Vanur Taluk, Villupuram District 605109'},
    {key:'1407', label:'G K M College of  Engineering and Technology, Alappakkam-Mappedu Road, Chennai 600063'},
    {key:'1408', label:'I F E T College of Engineering (Autonomous), Gangarampalayam, Villupuram District 605108'},
    {key:'1409', label:'Karpagavinayaga College of Engineering and Technology, Palayanoor Post, Maduranthagam Taluk, Chengalpattu District 603308'},
    {key:'1411', label:'Madha Engineering College, Kundrathur, Chennai 600069'},
    {key:'1412', label:'Mailam Engineering College, Mailam, Villupuram District 604304'},
    {key:'1413', label:'Sri Venkateswaraa College Of Technology, BHB Nagar, Vadakkal Village, Pondur Post, Sriperumbudur Taluk, Kancheepuram District 602105'},
    {key:'1414', label:'Prince Shri Venkateshwara  Padmavathy Enginering College, Ponmar, Chennai 600048'},
    {key:'1415', label:'T S M Jain College of Technology, Melur Village, Kallakurichi, Kallakurichi District 606201'},
    {key:'1416', label:'Jaya Sakthi Engineering College, Thirunindravur, Chennai 602024'},
    {key:'1417', label:'Shri Andal Alagar College of Engineering, Mamandur, Chengalpattu District 603111'},
    {key:'1419', label:'Sri Sairam Enginering College, West Tambaram, Chennai 600044'},
    {key:'1420', label:'Tagore Engineering College, Rathnamangalam, Vandalur Post, Chennai 600048'},
    {key:'1421', label:'V R S College of Engineering and Technology, Arasur, Kallakurichi District 607107'},
    {key:'1422', label:'SRM Valliammai Engineering College (Autonomous), Kattankulathur, Chennai 603203'},
    {key:'1424', label:'Dhaanish Ahmed College of Engineering, Padappai, Chennai 601301'},
    {key:'1426', label:'Sri Ramanujar Engineering College, Vandalur, Kolappakkam, Chennai 600048'},
    {key:'1427', label:'Sri Krishna Engineering College, Panappakkam, Padappai, Chennai 601301'},
    {key:'1428', label:'E S Engineering College, Chennai Trunk Road, Ayyankoilpattu, Villupuram District 605602'},
    {key:'1430', label:'Maha Bharathi Engineering College, A Vasudevanur, Chinnasalem, Kallakurichi Taluk, Kallakurichi District 606201'},
    {key:'1431', label:'New Prince Shri Bhavani College of Engineering and Technology, Vengaivasal Main Road, Gowriwakkam, Chennai 600073'},
    {key:'1432', label:'Rajalakshmi Institute of Technology, Irulapalayam, Kuthampakkam Post, Thiruvallur District 602107'},
    {key:'1434', label:'Surya Group of Institutions, GST Road, Vikravandi Village, Villupuram District 605652 '},
    {key:'1435', label:'Balaji Institute of Engineering and Technology, Thandalam Village, Thiruporur, Chengalpattu District 603110'},
    {key:'1436', label:'A R Engineering College, Vadakuchipalayam, Kappiyampuliyur Post, Villupuram District 605601'},
    {key:'1437', label:'Rrase College of Engineering, Padappai, Chennai 601301'},
    {key:'1438', label:'Sree Krishna College of Engineering, Anaicut Post, Unnai Village, Vellore District 632101'},
    {key:'1439', label:'S R I College of Engineering and Technology, Birudur, Vandavasi Taluk, Thiruvannamalai District 604408'},
    {key:'1441', label:'A K T Memorial College of Engineering and Technology, Neelamangalam Village, Kallakurichi Post & Taluk, Kallakurichi District 606202'},
    {key:'1442', label:'Prince Dr. K Vasudevan College of Engineering and Technology, Medavakkam-Mambakkam Road, Ponmar, Chennai 600048'},
    {key:'1444', label:'Chendu College of Engineering & Technology, Zamin Endathur Village, Madurantakam Taluk, Chengalpattu District 603331'},
    {key:'1445', label:'Sri Rangapoopathi College of Engineering, Alampoondi Village, Gingee, Villupuram District 604151'},
    {key:'1447', label:'Jawahar Engineering College, Kaveri Rangan Nagar, Saligramam, Chennai 600093'},
    {key:'1449', label:'Saraswathy College of Engineering and Technology, NH-45, Main Road, Olakkur, Tindivanam Taluk, Villupuram District 604307'},
    {key:'1450', label:'Loyola-ICAM College of Engineering and Technology, Loyola College Campus, Nungambakkam, Chennai 600034'},
    {key:'1452', label:'PERI Institute of Technology, Mannivakkam, West Tambaram, Chennai 600048'},
    {key:'1501', label:'Adhiparasakthi College of Engineering, Kalavai, Vellore District 632506'},
    {key:'1503', label:'Arulmigu  Meenakshi Amman College of Engineering, Vadamavandal,Thiruvannamalai District 604410'},
    {key:'1504', label:'Arunai Engineering College, Mathur, Thiruvannamalai District 606603'},
    {key:'1505', label:'C Abdul Hakeem College of Engineering and Technology, Melvisharam, Vellore District 632509'},
    {key:'1506', label:'G G R College of Engineering, Pillayarkuppam, Perumugai Post, Vellore District 632009'},
    {key:'1507', label:'Ganadipathy Tulsi’s Jain Engineering College, Kaniyambadi, Vellore District 632102'},
    {key:'1508', label:'Arunai College of Engineering, Mathur, Thiruvannamalai District 606603'},
    {key:'1509', label:'Meenakshi College of Engineering, Vembuliamman Koil Street, K K Nagar (West), Chennai 600078'},
    {key:'1510', label:'Priyadarshini Engineering College, Vaniyambadi Post, Thirupattur District 635751'},
    {key:'1511', label:'Ranippettai Engineering College, Thenkadappanthangal, Vellore District 632513'},
    {key:'1512', label:'S K P Engineering College, Thiruvannamalai District 606611'},
    {key:'1513', label:'Sri Balaji Chockalingam Engineering College, Arni, Thiruvannamalai District 632317'},
    {key:'1514', label:'Sri Nandhanam College of Engineering and Technology, Tiruppattur, Tiruppattur District 635601'},
    {key:'1515', label:'Saraswathi Velu College of Engineering, Melvenkatapuram Village, Sholingur, Vellore District 631102'},
    {key:'1516', label:'Thanthai Periyar Government Institute of Technology , Bagayam, Vellore District 632002'},
    {key:'1517', label:'Thirumalai Engineering College, Kilambi, Kancheepuram District 631551'},
    {key:'1518', label:'Thiruvalluvar College of Engineering and Technology, Vandavasi, Thiruvannamalai District 604505'},
    {key:'1519', label:'Bharathidasan Engineering College, Nattrampalli Post, Tiruppattur District 635854'},
    {key:'1520', label:'Kingston Engineering College, Chithoor Main Road, Christianpet Village, Katpadi Taluk,  Vellore District 632059'},
    {key:'1521', label:'Sri Sapthagiri Institute of Technology, Ocheri, Arakonam Taluk, Vellore District 632531'},
    {key:'1523', label:'Global Institute of Engineering and Technology, Bangalore-Chennai Highway, Melvisharam, Walajah Taluk, Vellore District 632506'},
    {key:'1524', label:'Annamalaiar College of Engineering, Modaiyur Village, Polur Taluk, Thiruvannamalai District 606902'},
    {key:'1525', label:'Podhigai College of Engineering and Technology, Vinayakapuram, Adiyur Post, Tirupattur Taluk, Tiruppattur District 635601'},
    {key:'1526', label:'Sri Krishna College of Engineering, Tiruttani High Road, Arakkonam, Vellore District 631003'},
    {key:'1529', label:'Oxford College of Engineering, Venmani Village, Karaipoondi Post, Polur Taluk, Thiruvannamalai District 606803'},

    {key: '1530', label: 'Papni School of Architecture, 302/1, Keeranallur Village, Sriperunbudur Taluk, Kancheepuram District, Chennai 602108' },


    {key:'1605', label:'Idhaya Engineering College for Women, Chinnasalem, Kallakurichi District 606201'},
    {key:'2005', label:'Government College of Technology (Autonomous), Thadagam Road, Coimbatore District 641013'},
    {key:'2006', label:'PSG College of Technology (Autonomous), Peelamedu, Coimbatore District 641004'},
    {key:'2007', label:'Coimbatore Institute of Technology (Autonomous), Civil Aerodrome Post, Coimbatore District 641014'},
    {key:'2025', label:'Anna University Regional Campus - Coimbatore, Maruthamalai Main Road, Navavoor Bharathiyar University Post, Somayampalayam, Coimbatore District 641046'},
    {key:'2302', label:'Sri Shanmugha College of Engineering and Technology, Morur Bit II Village, Salem District 637302'},
    {key:'2314', label:'Muthayammal College of Engineering, Kakkaveri Post, Namakkal District 637408'},
    {key:'2327', label:'N S N College of Engineering and Technology, Karur-Madurai NH7, Manalmedu, Karur District 639003'},
    {key:'2328', label:'K S R Institute for Engineering and Technology, Thokkavadi, Namakkal District 637215'},
    {key:'2329', label:'Rathinam Technical Campus, Pollachi Road, Eachanari, Coimbatore District 641021'},
    {key:'2332', label:'Aishwarya College of Engineering and Technology, Errattaikaradu Paruvachi Post, Anthiyur (Via), Bhavani Taluk, Erode District 638312'},
    {key:'2338', label:'Asian College of Engineering and Technology, Asian College Road, Kondayampalayam, Near Saravanampatti, Coimbatore District 641110'},
    {key:'2341', label:'Ganesh College of Engineering, Attur Main Road, Mettupatti, Salem District 636111'},
    {key:'2342', label:'Sri Ranganathar Institute of Engineering and Technology, Thudialur-Kovilpalay Road, Coimbatore District 641110'},
    {key:'2343', label:"Indian Institute of Handloom Technology, Foulke's Compound, Thillai Nagar, Salem District 636001"},
    
    {key: '2344', label: 'Kongu School of Architecture, Kongu Engineering College Campus, Perundurai Railway Station Road, Thoppupalayam Post, Perundurai, Erode District 638052' },
    
    {key:'2345', label:'Dhirajlal Gandhi College of Technology, Sikkanampatty, (Opp. to Airport), Omalur Taluk, Salem District 636309'},
    {key:'2346', label:'Shree Sathyam College of Engineering and Technology, NH-47, Manjakkalpatti, Kuppanur Post, Sankari Taluk, Salem District 637301'},
    {key:'2347', label:'AVS College of Technology, Attur Main Road, Near AVS College of Arts & Science, Chinnagoundapuram, Salem District 636106'},
    
    {key: '2348', label: 'San Academy of Architecture, ACC Pirivu, Navakarai Post, Mavuthampathy Village, Walayar, Coimbatore District 641105' },

    {key:'2349', label:'Dhaanish Ahmed Institute of Technology, Pichanur Post, (Near K G Chavadi), Coimbatore District 641105'},
    {key:'2350', label:'Jairupaa College of Engineering, Thottiapalayam, Kathankanni Post, Kangayam, Tiruppur District 641 604'},

    {key: '2351', label: 'N R School of Architecture, Kondampatty Village, Kinathukadavu, Pollachi Taluk, Coimbatore District 641202' },
    {key: '2352', label: 'J K K Munirajah School of Architecture, T N Palayam, Gobi Taluk, Erode District 638506' },

    {key:'2354', label:'Pollachi Institute of Engineering and Technology, Main Road, Poosaripatti, Pollachi Taluk, Coimbatore District 642205'},
    {key:'2355', label:'Cheran College of Engineering, Karur-Coimbatore Main Road, NH-67, K.Paramathi Post, Aravakurichi Taluk, Karur District 639111'},
    {key:'2356', label:'Arulmurugan College of Engineering, Karvazhi Road, Thennilai Post, Karur District 639206'},
    {key:'2357', label:'V S B College of Engineering Technical Campus, Ealur Pirivu, Solavampalayam Post, Coimbatore District 642109'},
    {key:'2358', label:'SCAD Institute of Technology, Anupatti, Pollachi-Palladam Highways, Palladam, Tiruppur District 641664'},
    {key:'2360', label:'Suguna College of Engineering, Kalappatti Road, Civil Aerodrome Post, Coimbatore District 641014'},

    {key: '2361', label: 'Sasi Creative School of Archiecture, Pollachi Main Road, Myleripalayam, Coimbatore District 641032' },

    {key: '2364', label: 'School Of Architecture Coimbatore Institute Of Engineering And Technology, Vellimalai Pattinam, Narasipuram Post, ThondamuthurVia,Coimbatore District 641109' },
    {key: '2365', label: 'Nehru School of Architecture, 451-D, Palakkad Main Road, Kuniamuthur, Coimbatore District 641108' },

    {key:'2367', label:'Arjun College of Technology, Chettiyakkapalayam, Kinathukadavu, Coimbatore District 642120'},
    {key:'2369', label:'Government College of Engineering, Chettikkarai Post, Dharmapuri District 635 704'},

    {key: '2372', label: 'Park Institute of Architecture, Avinashi Road, NH-47, Kaniyur, Coimbatore District 641659' },
    {key: '2373', label: 'Hindusthan School of Architecture, Othakkalmandabam Post, Coimbatore District 641032' },
    {key: '2376', label: 'Rathinam School of Architecture, Rathinam Techzone Campus Pollachi Road, Coimbatore District 641021' },

    {key:'2377', label:'PSG Institute of Technology and Applied Research, Avinashi Road, Neelambur, Coimbatore 641062'},
    {key:'2601', label:'Adhiyamaan  College of Engineering (Autonomous), Hosur, Krishnagiri District 635109'},
    {key:'2602', label:'Annai Mathammal Sheela Enginereing College, Erumapatty Post, Namakkal District 637013'},
    {key:'2603', label:'Government College of Engineering (Autonomous), Bargur, Krishnagiri District 635104'},
    {key:'2606', label:'Jayam College of Engineering and Technology, Nallanur Post, Dharmapuri District 636813'},
    {key:'2607', label:'K S Rangasamy College of Technology (Autonomous), Tiruchengode, Namakkal District 637215'},
    {key:'2608', label:'M Kumarasamy College of Engineering (Autonomous), Thalavapalayam, Karur District 639113'},
    {key:'2609', label:'Mahendra Engineering College (Autonomous), Mahendhirapuri, Mallasamudram, Namakkal District 637503'},
    {key:'2610', label:'Muthayammal Engineering College (Autonomous), Rasipuram, Namakkal District 637408'},
    {key:'2611', label:'Paavai Engineering College (Autonomous), NH-7, Pachal Post, Namakkal District 637018'},
    {key:'2612', label:'P G P College of Engineering and Technology, Paramathi Post, Namakkal District 637207'},
    {key:'2613', label:'K S R College of Engineering (Autonomous), Tiruchengode, Namakkal District 637215'},
    {key:'2614', label:'S S M College of Engineering, Komarapalayam, Namakkal District 638183'},
    {key:'2615', label:'Government College of Engineering (Autonomous), Karuppur, Salem District 636011'},
    {key:'2616', label:'Sapthagiri College of Engineering, Periyanahalli Post, Dharmapuri District 635205'},
    {key:'2617', label:'Sengunthar Engineering College (Autonomous), Tiruchengode, Namakkal District 637205'},
    {key:'2618', label:'Sona College of Technology (Autonomous), Suramangalam Post, Salem District 636005'},
    {key:'2620', label:'Vivekanandha College of Engineering for Women (Autonomous), Sathinaickenpalayam, Elayampalayam Village, Kumaramangalam, Namakkal District 637205'},
    {key:'2621', label:'Er. Perumal Manimekalai College of Engineering, Near Koneripalli, Hosur, Krishnagiri District 635117'},
    {key:'2622', label:'V S B Engineering College, Kovai Road, Karur District 639111'},
    {key:'2623', label:'Mahendra College of Engineering, Attur Road, Minnampalli, Valapady, Salem District 636106'},
    {key:'2624', label:'Gnanamani College of Technology, Pachal Post, Namakkal District 637018'},
    {key:'2625', label:'The Kavery Engineering College, M Kalipatti Post, Mecheri, Salem District 634453'},
    {key:'2627', label:'Selvam College of Technology, Pappanaickenpatti Post, Namakkal District 637003'},
    {key:'2628', label:'Paavai College of Engineering, NH-7, Pachal Post, Namakkal District 637018'},
    {key:'2629', label:'Sengunthar College of Engineering, Tiruchengode, Namakkal District 637205'},
    {key:'2630', label:'Chettinad College of Engineering and Technology, NH-67, Trichy Main Road, Puliyur C F, Karur District 639114'},
    {key:'2631', label:'King College of Technology, Nallur, N Pudupatty Post, Namakkal District 637020'},
    {key:'2632', label:'Mahendra Institute of Technology, Mahendhirapuri, Mallasamudram,  Namakkal District 637503'},
    {key:'2633', label:'Vidyaa Vikas College of Engineering and Technology, Varahoorampatti, Tiruchengode, Namakkal District 637 214'},
    {key:'2634', label:'Excel Engineering College, Pallakkapalayam, Sankari West Post, Namakkal District 637303'},
    {key:'2635', label:'C M S College of Engineering, Emapuram Post, Namakkal District 637003'},
    {key:'2636', label:'A V S Engineering College, Military Road, Ammapet, Salem District 636003'},
    {key:'2638', label:'Mahendra Engineering College for Women, Kumaramangalam, Namakkal District 637205'},
    {key:'2639', label:'Narasus Sarathy Institute of Technology, Poosaripatty Village, Omalur Taluk, Salem District 636305'},
    {key:'2640', label:'Jayalakshmi Institute of Technology, Thoppur, Dharmapuri District 635352'},
    {key:'2641', label:'Varuvan Vadivelan Institute of Technology, Nallanahalli, Dharmapuri District 636701'},
    {key:'2642', label:'P S V College of Engineeering and Technology, Mittapalli, Balinayanapalli Post, Elathagiri, Krishnagiri District 635108'},
    {key:'2643', label:'Bharathiyar Institute of Engineering for Women, Deviayakurichi, Attur Taluk, Salem District 636112'},
    {key:'2646', label:'Tagore Institute of Engineering and Technology, Deviyakurichi, Attur Taluk, Salem District 636112'},
    {key:'2647', label:'J K K Nataraja College of Engineering and Technology, Komarapalayam Amani, Thattankuttai Panchayat, Namakkal District 638183'},
    {key:'2648', label:'Annaporna Engineering College, Sankari Main Road, NH-47, Periaseeragapadi, Salem District 636308'},
    {key:'2649', label:'Karur College of Engineering, Sanjay Nagar, Karur-Erode Main Road, Athur Post, Karur District 639002'},
    {key:'2650', label:'Christ the King Engineering College, Cecilia Gardens, Chikkarampalayam Village, Coimbatore District 641104'},
    {key:'2651', label:'Jai Shriram Engineering College, Dharapuram Road, Avinashi Palayam, Tiruppur District 638660'},
    {key:'2652', label:'Al-Ameen Engineering College, Karundevan Palayam, Nanjai Uthukuli Post, Erode District 638104 '},
    {key:'2653', label:'Knowledge Institute of Technology, KIOT Campus, Kakapalayam Post, Salem District 637504'},
    {key:'2656', label:'Builders Engineering College,Erode Rode,Nathakadiyur, Kangeyam Taluk, Tiruppur District 638108'},
    {key:'2657', label:'Paavai College of Technology, NH-7, Pachal Post, Namakkal District 637018'},
    {key:'2658', label:'V S A Group of Institutions, NH-47, Uthamasola Puram Post, Salem District 636010'},
    {key:'2659', label:'Salem College of Engineering and Technology, Salem-Attur Main Road, NH-68, Mettupatty Perumapalayam, Salem District 636111'},
    {key:'2660', label:'Gnanamani College of Engineering, NH-7, A K Samuthiram, Pachal Post, Namakkal District 637018'},
    {key:'2661', label:'Vivekanandha College of Technology for Women, Sathinaickenpalayam, Elayampalayam Village, Kumaramangalam, Namakkal District 637205'},
    {key:'2662', label:'Dr. Nagarathinams College of Engineering, Anadhagoundam Palayam, Minakkal Post, Rasipuram, Namakkal District 637505'},
    {key:'2664', label:'Excel College of Engineering and Technology, Pallakapalayam, Sankari West Post, Namakkal District 637303'},
    {key:'2665', label:'Mahendra Institute of Engineering and Technology, Mahendrapuri, Mallasamudram, Namakkal District 637503'},
    {key:'2666', label:'The Kavery College of Engineering, M Kalipatti Post, Mecheri, Salem District 636453'},

    {key: '2667', label: 'Excel College of Architecture and Planning, Pallakapalayam, Sankari West Post, Namakkal District 637303' },

    {key:'2673', label:'Sree Sakthi Engineering College, Bettathapuram, Bilichi Village, Karamadai, Coimbatore District 641104'},
    {key:'2682', label:'Ambal Professional Group of Institutions, Coimbatore to Trichy Road, K N Puram Post, Palladam Taluk, Tiruppur District 641662'},
    {key:'2683', label:'Shreenivasa Engineering College, B Pallipatti, Bommidi, Pappireddipatti Taluk, Dharmapuri District 635301'},

    {key: '2684', label: 'TIPS School of Architecture, SF 361/1A, Karuvalur Road SS KulamPO, Coimbatore 6411407' },

    {key:'2702', label:'Bannari Amman Institute of Technology (Autonomous), Sathyamanagalam, Erode District  638401'},
    {key:'2704', label:'Coimbatore Institute of Engineering and Technolgoy (Autonomous), Narasipuram Post, Coimbatore District 641109'},
    {key:'2705', label:'C S I College of Engineering, Ketti, The Nilgiris 643215'},
    {key:'2706', label:'Dr. Mahalingam College of  Engineering and Technology (Autonomous), Mackinaickenpatti Post, Pollachi Taluk, Coimbatore District 642003'},
    {key:'2707', label:'Erode Sengunthar Engineering College (Autonomous), Thudupathi Post, Erode District 638057'},
    {key:'2708', label:'Hindusthan College of Engineering and Technology (Autonomous), Othakkalmandapam Post, Coimbatore District 641032'},
    {key:'2709', label:'Institute of Road and Transport Technology, Vasavi College Post, Erode District 638316'},
    {key:'2710', label:'Karpagam College of Engineering (Autonomous), Othakkalmandapam, Coimbatore District 641032'},
    {key:'2711', label:'Kongu Engineering College (Autonomous), Perundurai, Erode District 638052'},
    {key:'2712', label:'Kumaraguru College of Technology (Autonomous), Chinnavedampatti Post, Coimbatore District 641006'},
    {key:'2713', label:'M P Nachimuthu M Jagannathan Engineering College, Chennimalai, Erode District 638112'},
    {key:'2714', label:'Maharaja Engineering College, Avinashi, Tiruppur District 641654'},
    {key:'2715', label:'Nandha Engineering College (Autonomous), Pitchandampalayam Post, Erode District 638052'},
    {key:'2716', label:'Park College of Engineering and Technology, Kaniyur, Coimbatore District 641659'},
    {key:'2717', label:'Sasurie College of Engineering, Vijayamangalam, Tiruppur District 638056'},
    {key:'2718', label:'Sri Krishna College of Enginering and Technology (Autonomous), Kuniamuthur, Coimbatore District 641008'},
    {key:'2719', label:'Sri Ramakrishna Engineering College (Autonomous), Vattamalaipalayam, Coimbatore District 641022'},
    {key:'2721', label:'Tamilnadu College of Engineering, Karumathampatti Post, Coimbatore District 641659'},
    {key:'2722', label:'Sri Krishna College of Technology (Autonomous), Kovaipudur Post, Coimbatore District 641042'},
    {key:'2723', label:'Velalar College of Engineering and Technology (Autonomous), Thindal Post, Erode District 638009'},
    {key:'2725', label:'Sri Ramakrishna Institute of Technology (Autonomous), Pachapalayam, Coimbatore District 641010'},
    {key:'2726', label:'SNS College of Technology (Autonomous), Kalappatti Post, Coimbatore District 641035'},
    {key:'2727', label:'Sri Shakthi Institute of Engineering and Technology (Autonomous), L&T Bye-Pass, Venkitapuram Post, Comibatore District 641062'},

    {key: '2728', label: 'Tamilnadu School of Architecture, Karumathampatti Post, Coimbatore District 641659' },

    {key:'2729', label:'Nehru Institute of Engineering and Technology, Thirumalayampalayam Post, Coimbatore District 641105'},
    {key:'2731', label:'R V S College of Engineering and Technology, Kannampalayam, Sulur, Coimbatore District 641402'},
    {key:'2732', label:'INFO Institute of Engineering, Sarkar Samakulam, Coimbatore District 641107'},
    {key:'2733', label:'Angel College of Engineering and Technology, P.K.Palayam, Ugayanur Village, Tirupur District 641 665'},
    {key:'2734', label:'SNS College of Engineering, Sathy Main Road, Kurumbapalayam Post, Coimbatore District 641107'},
    {key:'2735', label:'Karpagam Institute of Technology, Seerapalayam Village, L&T By pass Road, Coimbatore District 641021'},
    {key:'2736', label:'Dr. N G P Institute of Technology, Kalapatti Road, Coimbatore District 641035'},
    {key:'2737', label:'Sri Sai Ranganathan Engineering College, Zahirnaickenpalayam Village, Viraliyur Post, Thondamuthur Via, Coimbatore District 641109'},
    {key:'2739', label:'Sri Eshwar College of Engineering (Autonomous), Kondampatti Post, Vadasithur (Via), Kinathukadavu, Coimbatore District 641202'},
    {key:'2740', label:'Hindustan Institute of Technology, Othakkalmandapam, Coimbatore District 641032'},
    {key:'2741', label:'P A College of Engineering and Technology (Autonomous), Palladam Road, Pollachi, Coimbatore District 642002'},
    {key:'2743', label:'Dhanalakshmi Srinivasan College of Engineering, NH47, Palakkad Main Road, Navakkarai Post, Near Nandhi Temple, Coimbatore District 641105'},
    {key:'2744', label:'Adithya Institute of Technology, Kurumbapalayam Village, Coimbatore District 641107'},
    {key:'2745', label:'Kathir College of Engineering, Neelambur, Avinashi Road, Coimbatore District 641062'},
    {key:'2747', label:'Shree Venkateshwara Hi-Tech Engineering College, Othakuthirai, K Mettupalayam Post, Gobichettipalayam, Erode District 638455'},
    {key:'2748', label:'Surya Engineering College, Mettukadai, Kathirampatti Post, Erode District 638107'},
    {key:'2749', label:'EASA College of Engineering and Technology, NH-47, Coimbatore-Palakkad Main Road, Navakarai Post, Coimbatore District 641105'},
    {key:'2750', label:'KIT-Kalaignar Karunanidhi Institute of Technology (Autonomous), Kannampalayam, Coimbatore District 641402'},
    {key:'2751', label:'KGISL Institute of Technology, KGISL Campus, Thudiyalur Road, Saravanampatti, Coimbatore District 641035'},
    {key:'2752', label:'Nandha College of Technology, Pitchandampalayam Post, Erode District 638052'},
    {key:'2753', label:'P P G Institute of Technology, Vilankurichi Village, Coimbatore District 641035'},
    {key:'2755', label:'Nehru Institute of Technology, Thirumalayampalayam Post, Coimbatore District 641105'},
    {key:'2758', label:'J K K Muniraja College of Technology, T N Palayam, Gobi Taluk, Erode District 638506'},

    {key: '2759', label: 'McGans Ooty School Of Architecture, Summer House Road, Ooty, The Nilgiris 643001' },

    {key:'2761', label:'United Institute of Technology, Gadalore Village, Perianaickenpalayam, Coimbatore District 641020'},
    {key:'2762', label:'Jansons Institute of Technology, Karumathampatty, Somaur, Coimbatore District 641659'},
    {key:'2763', label:'Akshaya College of Engineering and Technology, Kinathukadavu, Coimbatore District 642109'},
    {key:'2764', label:'K P R Institute of Engineering and Technology, Kollupalayam Village, Arasur Panchayat, Coimbatore District 641407'},
    {key:'2765', label:'Sriguru Institute of Technology, Varathaiyanagar Palayam, Kondayampalayam Post, Coimbatore District 641110'},
    {key:'2767', label:'SRG Engineering College, Aniyapuram Post, Namakkal District 637017'},
    {key:'2768', label:'Park College of Technology, Prema Ravi Nagar, Karumathampatty, Coimbatore District 641059'},
    {key:'2769', label:'J C T College of Engineering and Technology, Pichanur, Coimbatore District 641105'},
    {key:'2772', label:'C M S College of Engineering and Technology, Appachigoundenpathy, Kumittipatti, Coimbatore District 641105'},
    {key:'2776', label:'R V S Technical Campus-Coimbatore, Kumaran Kottam Campus,  Kannampalayam, Sulur, Coimbatore District 641 402'},

    {key: '2778', label: 'R V S School of Architecture, Kumaran Kottam Campus, Trichy Road, Kannampalayam, Coimbatore District 641402' },
    {key: '2779', label: 'Ranganathan Architecture College, Viraliyur Post, Thondamuthur Via, Coimbatore District 641109' },
    {key: '2780', label: 'S V S School of Architecture, Asarampalayam Post, Pollachi Taluk, Coimbatore District 642109' },

    {key:'3011', label:'University College of Engineering,BIT Campus,Anna university ,Tiruchirappalli District 620024'},
    {key:'3016', label:'University College of Engineering, Ariyalur, Kathankudikadu Village, Thelur Post, Ariyalur District 621704'},
    {key:'3018', label:'University College of Engineering, Thirukkuvalai, Nagappattinam District 610204'},
    {key:'3019', label:'University College of Engineering, Panruti, Chennai-Kumbakonam Highway, Panikkankuppam, Panruti, Cuddalore District 607106'},
    {key:'3021', label:'University College of Engineering, Pattukkottai, ECR Road, Rajamadam, Pattukkottai Taluk, Thanjavur District 614701'},
    {key:'3403', label:'Mahalakshmi Engineering College, Trichy-Salem Highways, (Near No.1 Tollgate), Melpathu, Siruganbur Post, Tiruchirappalli District 621213'},
    {key:'3410', label:'Krishnaswamy Collge of Engineering and Technology, S Kumarapuram, Cuddalore District 607109'},
    {key:'3425', label:'C K College of Engineering and Technology, Chellangkuppam, Cuddalore District 607003'},

    {key: '3446', label: 'Prime College of Architecture and Planning, Main Road, Kilvelur, Nagapattinam District 611104' },

    {key:'3451', label:'SMR East Coast College of Engineering & Technology, East Coast Road, Somanathapattinam, Thanjavur District 614612'},
    
    {key: '3453', label: 'RVS KVK School of Architecture, Dindigul Highway, Inamkulathur, Tiruchirappalli District 621303' },

    {key:'3454', label:'Sri Ramakrishna College of Engineering, Sri Saradha Nagar, NH-45, Perambalur District  621113'},
    {key:'3456', label:'K S K College of Engineering and Technology, Thanjavur Main Road, Darasuram, Kumbakonam, Thanjavur District 612702'},
    {key:'3457', label:'Dhanalakshmi Srinivasan College of Engineering, Thuraiyur Road, Perambalur District 621212'},
    {key:'3458', label:'Dhanalakshmi Srinivasan Institute of Research and Technology, NH-45, Trichy–Chennai Main Road, Siruvachur, Perambalur District 621113'},
    {key:'3459', label:'Dhanalakshmi Srinivasan Institute of Technology,  Samayapuram, Chennai-Trichy Main Road, Tiruchirappalli District 621112'},
    {key:'3460', label:'Sureya College of Engineering, Konalai, Tiruchirappalli District 621132'},
    {key:'3461', label:'Arifa Institute of Techonology, Esanoor, Keelaiyur Post, Thirukkuvalai Taluk, Nagapattinam District 611103'},
    {key:'3462', label:'Ariyalur Engineering College, NH-227, Trichy-Chithambaram NH, Karuppur-Senapathy Post, Ariyalur District 621707'},
    {key:'3463', label:'Elizabeth College of Engineering and Technology, Annamangalam Post, Veppanthattai Taluk, Perambalur District 621102'},
    {key:'3464', label:'Government College of Engineering, Gandarvakottai Road, Sengipatti, Thanjavur District 613402'},
    {key:'3465', label:'Government College of Engineering, Srirangam, Sethurappatti,  Trichy District 620 012'},
    {key:'3466', label:'Nelliandavar Institute of Technology, Nerunjikorai Village, Pudhupalayam, Ariyalur Taluk, Ariyalur District 621704'},

    {key: '3467', label: 'Prime Nest College of Architecture and Planning, V.J.P. Campus, Trichy-Chennai Highway, Navaladiyan Nagar, Siruganur, Tiruchirappalli District 621105' },

    {key:'3701', label:'K Ramakrishnan College of Technology, Kariyamanickam Road, Samayapuram, Manachanallur Taluk, Tiruchirappalli District 621112'},
    {key:'3760', label:'Sir Issac Newton College of Engineering and Technology, Anthanapeetai Post, Papakoil, Nagappattinam District 611102'},
    {key:'3766', label:'Star Lion College of Engineering & Technology, Manankorai Main Road, Manankorai Village, Thanjavur District 614206'},
    {key:'3782', label:'OASYS Institute of Technology , Pulivalam Village, Musiri Taluk, Tiruchirappalli District 626001'},

    {key: '3783', label: 'M.A.M. School of Architecture, Siruganur, Tiruchirappalli District 621105' },
    {key: '3784', label: 'C.A.R.E School of Architecture, Engineering, Thayanoor Village, Kuttappatti, Srirangam Taluk, Tiruchirappalli District 620009' },

    {key:'3786', label:'M.A.M. School of Engineering, Siruganur, Tiruchirappalli District 621105'},
    {key:'3795', label:'SRM TRP Engineering College, Irungalur, Manachanallur Taluk, Tiruchirappalli District 621105'},
    {key:'3801', label:'A V C College of Engineering, Mannampandal Post, Mayiladuthurai, Nagappattinam District 609305'},
    {key:'3802', label:'Shri Angalamman College of Engineering and Technology  Siruganoor, Tiruchirappalli District 621105'},
    {key:'3803', label:'Anjalai Ammal-Mahalingam Engineering College, Kovilvenni, Thiruvarur District 614403'},
    {key:'3804', label:'Arasu Engineering  College, Chennai Main Road, Kumbakonam, Thanjavur District 612501'},
    {key:'3805', label:'Dhanalakshmi Srinivasan  Engineering College, Thuraiyur Road, Perambalur District 621212'},
    {key:'3806', label:'E G S Pillay  Engineering College (Autonomous), Nagapattinam District 611002'},
    {key:'3807', label:'J J College of Engineering and Technology, Poolankulathupatti Post, Thiruchirappalli District 620009'},
    {key:'3808', label:'Jayaram College of Engineering and Technology , Pagalavadi Post, Tiruchirappalli District 621014'},
    {key:'3809', label:'Kurinji College of Engineering and Technology, Manapparai, Tiruchirappalli District 621307'},
    {key:'3810', label:'M.A.M. College of Engineering, Siruganur, Tiruchirappalli District 621105'},
    {key:'3811', label:'M I E T Engineering College, Trichy-Pudukkottai Road, Tiruchirappalli District 620007'},
    {key:'3812', label:'Mookambigai College of Engineering, Keeranur, Pudukkottai District 622502'},
    {key:'3813', label:'Oxford Engineering College, Pirattiyur(W), Tiruchirappalli District 620009'},
    {key:'3814', label:'P R Engineering College, Vallam, Thanjavur District 613403'},
    {key:'3815', label:'Pavendhar Bharathidasan College of Engineering and Technology, Pudukkottai Main Road, Tiruchirappalli District 620024'},
    {key:'3817', label:'Roever Engineering College, Elambalur, Perambalur District 621212'},
    {key:'3819', label:'Saranathan College of  Engineering, Panjappur, Tiruchirappalli District  620012'},
    {key:'3820', label:'Trichy Engineering College, Konalai, Tiruchirappalli District 621132'},
    {key:'3821', label:'A R J College of Engineering and Technology, Mannargudi Taluk, Thiruvarur District 614001'},
    {key:'3822', label:'Dr. Navalar Nedunchezhian College of Engineering, Tholudur, Cuddalore District 606303'},
    {key:'3823', label:'Srinivasan Engineering College, Thuraiyur Road, Perambalur District 621212'},
    {key:'3825', label:'St. Josephs College Of Engineering And Technology, Elupatti Village, Rawaspatti Post, Thanjavur District 613403'},
    {key:'3826', label:'Kongunadu College of Engineering and Technology, Tholurpatti, Thottiyam, Tiruchirappalli District 621215'},
    {key:'3829', label:'M.A.M. College of Engineering and Technology, Trichy-Chennai Trunk Road, Siruganur, Tiruchirappalli District 621105'},
    {key:'3830', label:'K Ramakrishnan College of Engineering, Kariyamanickam Road, Samayapuram, Manachanallur Taluk, Tiruchirappalli District 621112'},
    {key:'3831', label:'Indra Ganesan College of Engineering, Madurai Main Road, Manikandam, Tiruchirappalli District 620012'},
    {key:'3833', label:'Parisutham Institute of Technology and Science, Ring Road, Nanjikottai, Thanjavur District 613006'},
    {key:'3841', label:'C.A.R.E Group of Institutions, Thayanoor Village, Thayanoor Village, Kuttappatti, Srirangam Taluk, Tiruchirappalli District 620009'},
    {key:'3843', label:'M R K Institute of Technology, Nattarmangalam Village, Kattumannarkoil, Cuddalore District 608306'},
    {key:'3844', label:'Shivani Engineering College, Ammapettai, Srirangam, Tiruchirappalli District 620009'},
    {key:'3845', label:'Imayam College of Engineering, Kannanur, Thuraiyur, Tiruchirappalli District 621206'},
    {key:'3846', label:'Mother Terasa College of Engineering and Technology, Mettusalai Post and Taluk, Pudukkottai District 622102'},
    {key:'3847', label:'Roever College of Engineering and Technology, Elambalur, Perambalur District 621212'},
    {key:'3848', label:'Vandayar Engineering College, Pulavarnatham Post, Mariamman Koil (Via), Thanjavur District 613001'},
    {key:'3849', label:'Annai College of Engineering and Technology, Kovilacheri, Kumbakonam, Thanjavur District 612503'},
    {key:'3850', label:'Vetri Vinayaha College of Engineering and Technology, Namakkal-Trichy Main Road, Tholurpatti Village, Thottiam, Tiruchirappalli District 621215'},
    {key:'3852', label:'Sri Bharathi Engineering College for Women, Kaikkuruchi Village, Alangudi Taluk, Pudukkottai District 622303'},
    {key:'3854', label:'Mahath Amma Institute of Engineering and Technology (MIET), Ariyur, Annavasal Road, Illupur Taluk, Pudukkottai District 622101'},
    {key:'3855', label:'As-Salam College of Engineering and Technology, Thirumangalakudi, Aduthurai, Thiruvidaimaruthur, Thanjavur District 612102'},
    {key:'3857', label:'Meenakshi Ramaswamy Engineering College, Trichy Main Road,  Thathanur, Udayarpalayam, Ariyalur District 621804'},
    {key:'3859', label:'Sembodai Rukmani Varatharajan Engineering College, Sembodai Village, Vedaraniam, Nagappattinam District 614820'},
    {key:'3860', label:'St. Annes College of Engineering and Technology, Anguchettypalayam, Siruvathur Post, Panruti, Cuddalore District 607110'},
    {key:'3905', label:'Kings College of Engineering, Punalkulam, Pudukkottai District 613303'},
    {key:'3908', label:'Mount Zion College of Engineering and Technology, Pilivalam Post, Pudukkottai District 622507'},
    {key:'3918', label:'Shanmuganathan Engineering College, Pillivalam Post, Pudukkottai District 622507'},
    {key:'3920', label:'Sudharsan Engineering College, Sathiyamangalam Post, Pudukkottai District 622501'},
    {key:'3923', label:'M N S K College of Engineering, Vallathirakkottai Post, Pudukkottai District 622305'},
    {key:'3925', label:'M A R College of Engineering and Technology, Boothakudi, Rasanaickenpatty Post, Illuppur Taluk, Pudukkottai District 621316'},
    {key:'4020', label:'Anna University Regional Campus - Tirunelveli, Trivandrum Road, Palayamkottai, Tirunelveli District 627007'},
    {key:'4023', label:'University College of Engineering, Nagercoil, Nagercoil Industrial Estate, Konam, Kanyakumari District 629004'},
    {key:'4024', label:'University V.O.C. College of Engineering, Thoothukudi, Near V.O.C. College, Millerpuram, Thoothukudi District 628008'},
    {key:'4669', label:'Thamirabharani Engineering College, Chathirampudukulam Village, Thatchanallur, Tirunelveli District 625358'},
    {key:'4670', label:'Rohini College of Engineering & Technology, Anjugramam-Kanyakumari Main Road, Palkulam, Variyoor Post, Kanyakumari District 629401'},

    {key: '4671', label: 'Sigma College of Architecture, Moododu, Anducode Post, Marthandam, Kanyakumari District 629168' },

    {key:'4672', label:'Stella Marys College of Engineering, Arunthengan Vilai, Azhikal Post, Kanyakumari District 629202'},
    {key:'4675', label:'Universal College of Engineering and Technology, Anbagam Campus, Radhapuram Road, Vallioor, Tirunelveli District 627117'},
    {key:'4676', label:'Renganayagi Varatharaj College of Engineering, Salvarpatti, Sivakasi, Virudhunagar District 626128'},
    {key:'4677', label:'Lourdes Mount College of Engineering and Technology, Marthandam-Karungal Road, Chundavilai, Mullanganavilai, Nattalam Post, Kanyakumari District 629195'},
    {key:'4678', label:'Ramco Institute of Technology, North venganallur Village, Krishnapuram Panchayat, Rajapalayam, Virudhunagar District 626117'},

    {key: '4679', label: 'V.P.M.M. College of Architecture for Women, V.P.M. Nagar, Krishnankoil, Srivilliputtur, Virudhunagar District 626190' },

    {key:'4680', label:'AAA College of Engineering and Technology, Kamarajar Educational Road, Amathur Village, Sivakasi, Virudhunagar District 626005'},
    {key:'4686', label:'Good Shepherd College of Engineering and Technology, Maruthamparai, Kanyakumari District 629101'},
    {key:'4864', label:'V V College of Engineering, Arasoor Village, Idaichivilai Post, Santhakulam Taluk, Thoothukudi District 628656'},
    {key:'4917', label:'Sethu Institute of Technology (Autonomous), Kariapatti Post, Virudhunagar District 626106'},
    {key:'4927', label:'Maria College of Engineering and Technology, Attoor Puliyamoodu Junction, Thiruvattar Post, Kanyakumari District 629177'},
    {key:'4928', label:'MAR Ephraem College of Engineering & Technology, Malankara Hills, Elavuvillai, Marthandam, Kanyakumari District 629171 '},
    {key:'4929', label:'M E T Engineering College, Mogals Garden, Thovalai Village, Aralvaimozhi Town Panchayat, Thovalai, Kanyakumari District 629304'},
    {key:'4931', label:'Chandy College of Engineering, Chandy Nagar, Mullakkadu, Thoothukudi District 628005'},
    {key:'4932', label:'Immanuel Arasar J J College of Engineering, Anappara, Edavilagam, Nattalam, Kanyakumari District 629195'},
    {key:'4933', label:'St. Mother Theresa Engineering College, Vagaikulam, Thoothukudi District 628102'},
    {key:'4934', label:'Holy Cross Engineering College, Vagaikulam, Sri Mulakarai, Srivaikuntam,  Thoothukudi District 628851'},
    {key:'4937', label:'A R College of Engineering and Technology, Kadayam-Alangulam Road, Therikkumadathoor Post, Tirunelveli District 627423'},
    {key:'4938', label:'Sivaji College of Engineering and Technology, Manivilla Palulai Panchayat, Vilavancode, Kanyakumari District 629170'},
    {key:'4941', label:'Unnamalai Institute of Technology, Ayyaneri, Kovilpatti, Thoothukudi District 628502'},
    {key:'4943', label:'Satyam College of Engineering & Technology, Kannappannallur, Aralvaimozhi, Kanyakumari District 629301'},
    {key:'4944', label:'Arunachala College of Engineering for Women, Thanka Gardens, Manavilai, Vellichanthai, Nagercoil, Kanyakumari District 629203'},
    {key:'4945', label:'Vins Christian Womens College of Engineering, Chunkankadai Post, Nagercoil, Kanyakumari District 629807'},
    {key:'4946', label:'D M I Engineering College, Aralvaimozhi Village, Thovalai, Kanyakumari District 629301'},
    {key:'4948', label:'Rajas International Institute of Technology for Women, Ozhuginasery, Nagercoil, Kanyakumari District 629001'},
    {key:'4949', label:'P S N Institute of Technology & Science, Melathediyoor, Tirunelveli District 627152'},
    {key:'4952', label:'C S I Institute of Technology, Thovalai, Kanyakumari District 629302'},
    {key:'4953', label:'CAPE Institute of Technology, Levingipuram, Tirunelveli District 627114'},
    {key:'4954', label:'Dr. Sivanthi Aditanar College of Engineering, Tiruchendur, Thoothukudi District 628215'},
    {key:'4955', label:'Francis Xavier Engineering College, Vannarpettai, Tirunelveli District 627003'},
    {key:'4957', label:'Jayaraj Annapackiam CSI College of Engineering, Nazareth, Thoothukudi District 628617'},
    {key:'4959', label:'Kamaraj College of Engineering and Technology, Virudhunagar District 626001'},
    {key:'4960', label:'Mepco Schlenk Engineering College (Autonomous), Sivakasi, Virudhunagar District 626005'},
    {key:'4961', label:'National College of Engineering, Maruthakulam Post, Tirunelveli District 627151'},
    {key:'4962', label:'National  Engineering College (Autonomous), Kovilpatti, Thoothukudi District 628503'},
    {key:'4964', label:'P S N College of Engineering and Technology (Autonomous), Melathediyoor, Tirunelveli Dstrict 627152'},
    {key:'4965', label:'P S R  Engineering College (Autonomous), Appayanaickenpatti, Sevalpatti, Virudhunagar District 626140'},
    {key:'4966', label:'PET Engineering College, Vallioor Post, Tirunelveli District 627117'},
    {key:'4967', label:'S Veerasamy Chettiar College of  Engineering and Technology, Puliangudi Post, Tenkasi District 627855'},
    {key:'4968', label:'Sardar Raja College of Engineering, Alangulam,  Tenkasi District 627808'},
    {key:'4969', label:'SCAD College of Engineering and Technology, Cheranmahadevi, Tirunelveli District 627414'},
    {key:'4970', label:'Sree Sowdambiga  College of Engineering, Aruppukkottai Taluk, Virudhunagar District 626134'},
    {key:'4971', label:'St. Xavier Catholic College of Engineering, Chunkankadai, Nagercoil, Kanyakumari District 629807'},
    {key:'4972', label:'Amrita College of Engineering and Technology, Erachakulam Post, Kanyakumari District 629902'},
    {key:'4973', label:'Rajas Engineering College , Vadakkangulam, Tirunelveli District 627116'},
    {key:'4974', label:'Government College of Engineering, Tirunelveli District 627007'},
    {key:'4975', label:'Dr. G U Pope College of Engineering, Sawyerpuram, Thoothukudi District  628251'},
    {key:'4976', label:'Infant Jesus College of Engineering, Thoothukudi Highway (NH7/A), Thoothukudi District 628851'},
    {key:'4977', label:'Narayanaguru College of Engineering, Manjalumoodu, Kanyakumari District 629151'},
    {key:'4978', label:'Udaya School of Engineering, Ammandivilai Post, Kanyakumari District 629204'},
    {key:'4979', label:'V P Muthaiah Pillai Meenakshi Ammal Engineering College for Women, Srivilliputhur Taluk, Virudhunagar District 626190'},
    {key:'4980', label:'Einstein College of Engineering, Seethaparpanallur, Tirunelveli District 627012'},
    {key:'4981', label:'Ponjesly College of  Engineering, Vettornimadam Post, Nagercoil, Kanyakumari District 629003'},
    {key:'4982', label:'Vins Christian College of Engineering, Chunkankadai Post, Nagercoil, Kanyakumari District  629807'},
    {key:'4983', label:'Lord Jegannath College of Engineering and Technology, Kumarapuram, Thoppur Post, Kanyakumari District 629402'},
    {key:'4984', label:'Marthandam College of Engineering & Technology, Kuttakuzhi, Veeyanoor Post, Kanyakumari District 629177'},
    {key:'4989', label:'P S N Engineering College, Melathediyoor, Tirunelveli District 627152'},
    {key:'4992', label:'Bethlahem Institute of Engineering, Karungal, Kanyakumari District 629157'},
    {key:'4993', label:'Loyola Institute of Technology and Science, Loyola Nagar,  P B No.2, Thovalai, Kanyakumari District 629302'},
    {key:'4994', label:'J P College of Engineering, College Road, Ayakudy, Tenkasi Taluk,  Tenkasi District 627852'},
    {key:'4995', label:'P S R Rengasamy College of Engineering for Women, Appayanaickenpatti, Sevalpatti, Virudhunagar District 626140'},
    {key:'4996', label:'Sri Vidhya College of Engineering and Technology, Sivakasi Main Road, P Kumaralinapuram, Virudhunagar District 626005'},
    {key:'4998', label:'Mahakavi Bharathiyar College of Engineering and Technology, Vasudevanallur, Tenkasi District 627758'},
    {key:'4999', label:'Annai Vailankanni College of Engineering, Pothaiyadi Salai, Pottalkulam, Azhagappapuram, Kanyakumari District 629401'},
    {key:'5008', label:'Thiagarajar College of Engineering (Autonomous), Tirupparankundram, Madurai District 625015'},
    {key:'5009', label:'Government College of Engineering,  Melachokkanathapuram, Bodinayakkanur, Theni District 625 582'},
    {key:'5010', label:'Anna University Regional Campus - Madurai, Kanyakumari National Highway, Keelakuilkudi, Madurai District 625019'},
    {key:'5012', label:'Central Electrochemical Research Institute, (CECRI), Karaikudi, Sivagangai District 630006'},
    {key:'5017', label:'University College of Engineering, Ramanathapuram, Pullangudi, Ramanathapuram District 623513'},
    {key:'5022', label:'University College of Engineering, Dindigul, Mangarai Pirivu, Reddiyarchathiram, Dindigul District 624622'},
    {key:'5502', label:'Sree Raaja Raajan College of Engineering & Technology, Amaravathi Village, Amaravathi Pudur Post, Karaikudi, Sivagangai District 630301'},
    {key:'5530', label:'SSM Institute of Engineering and Technology, Kuttathupatti Village, Sindalaigundu Post, Dindigul District 624002'},
    {key:'5532', label:'Vaigai College of Engineering, Therkutheru, Melur Taluk, Madurai District 625122'},
    {key:'5533', label:'Karaikudi Institute of Technology, KIT & KIM Technical Campus, Keeranipatti, Thalakkuvur, Karaikudi, Sivagangai District 630307'},
    {key:'5536', label:'Mangayarkarasi College of Engineering, First Street, Mangayarkarasi Nagar, Paravai, Madurai District 625402'},
    {key:'5537', label:'Jainee College of Engineering and Technology, Dindigul-Theni Main Road (Near Vakkampatti), Dindigul District 624303'},

    {key: '5538', label: 'J.K. College of Architecture, NH-7, Madurai Road, Begampur Post, Dindigul 624002' },
    {key: '5544', label: 'Agni School of Architecture and Design Excellence (ASADE), NH45, Trichy Road, Morepatti, Vadamadurai, Dindigul District 624001' },


    {key:'5703', label:'Christian College of Engineering and Technology, Oddanchatram, Dindigul District 624619'},
    {key:'5720', label:'Sri Subramanya College of Engineering and Technology, Sukkamanaickanpatti, Palani, Dindigul District 624615'},
    {key:'5832', label:'N P R College of Engineering and Technology, Natham, Dindigul District 624003'},
    {key:'5842', label:'Madurai Institute of Engineering & Technology, Pottapalayam Village, Manamadurai Taluk, Sivagangai District 630611 '},
    {key:'5851', label:'Veerammal Engineering College, K Singarakottai, Dindigul District 624708'},
    {key:'5862', label:'R V S Educational Trust’s Groups of Institutions (Integrated Campus), N Paraipatti Post, Vedasandur Taluk, Dindigul District 624005'},

    {key: '5863', label: 'R V S School of Architecture, N Paraipatti Post, Vedasandur Taluk, Dindigul District 624005' },

    {key:'5865', label:'Nadar Saraswathi College of Engineering and Technology, Vadupudupatti, Annanji Post, Theni District 625531'},
    {key:'5901', label:'Alagappa Chettair Government College of Engineering and Technology (Autonomous), Karaikudi, Sivagangai District 630004'},
    {key:'5902', label:'Bharath Niketan Engineering College, Thimmarasanaickanoor, Aundipatti, Theni District 625536'},
    {key:'5903', label:'K L N College of Information Technology, Pottapalayam, Sivagangai District  630611'},
    {key:'5904', label:'K L N College of Engineering, Pottapalayam, Sivagangai District 630611'},
    {key:'5907', label:'Mohamed Sathak Engineering College, Kilakarai, Ramanathapuram District 623806'},
    {key:'5910', label:'P S N A Colllege of Engineering and Technology, Dindigul District 624622'},
    {key:'5911', label:'P T R College of Engineering and Technology, Austinpatty Post, Madurai District 625008'},
    {key:'5912', label:'Pandian Saraswathi Yadav Engineering College, Thirumansolai Post, Sivagangai District 630 561'},
    {key:'5913', label:'Ratnavel Subramaniam College of Engineering and Technology, N Paraipatti Post, Dindigul District 624005'},
    {key:'5914', label:'SOLAIMALAI COLLEGE OF ENGINEERING, Veerapanjan, Madurai District 625020'},
    {key:'5915', label:'SACS-M A V M M Engineering College, Kidaripatty Post, Madurai District 625001'},
    {key:'5919', label:'St. Michael College of Engineering and Technology, Kalayarkoil, Sivagangai District 630551'},
    {key:'5921', label:'Syed Ammal Engineering College, Achunthanvayal Post, Ramanathapuram District-623502'},
    {key:'5922', label:'Vickram College of Engineering, Enathi Post, Sivagangai District 630561'},
    {key:'5924', label:'Ganapathy Chettiar College of Engineering and Technology, Melakavanur Post, Paramakudi, Ramanathapuram District 623706'},
    {key:'5930', label:'SBM College of Engineering and Technology, Thamaraipady, T N Paraipatti Pirivu, Dindigul District 624005'},
    {key:'5935', label:'Fatima Michael College of Engineering & Technology, Sengottai Village, Sivagangai Main Road, Madurai District 625020'},
    {key:'5942', label:'Ultra College of Engineering & Technology , Kodikulam, 1 Bit Village, Madurai-Chennai Highway, Madurai District 625104'},
    {key:'5986', label:'Velammal College of Engineering and Technology, Madurai - Rameshwaram High Road, Viraganoor, Madurai District 625009'},
    {key:'5988', label:'Theni Kammavar Sangam College of Technology, Theni Main Road, Koduvillarpatti Post, Theni District 625534'},
    {key:'5990', label:'Latha Mathavan Engineering College, Kidaripatti Post, Alagarkoil (Via), Melur Taluk, Madurai District 625301'}];

    const DEPT_LIST = [
        {key:"AD", label:"Artificial Intelligence and Data Science"},
{key:"AE", label:"AERONAUTICAL ENGINEERING"},
{key:"AG", label:"AGRICULTURE ENGINEERING"},
{key:"AL", label:"Artificial Intelligence and Machine Learning"},
{key:"AM", label:"COMPUTER SCIENCE AND ENGINEERING (AI AND MACHINE LEARNING)"},
{key:"AO", label:"AEROSPACE ENGINEERING"},
{key:"AP", label:"APPAREL TECHNOLOGY (SS)"},
{key:"AR", label:"ARCHITECTURE"},
{key:"AS", label:"AUTOMOBILE ENGINEERING (SS)"},
{key:"AU", label:"AUTOMOBILE ENGINEERING"},
{key:"BA", label:"ARCHITECTURE (SS)"},
{key:"BC", label:"Bio Technology and Bio Chemical Engineering"},
{key:"BD", label:"COMPUTER SCIENCE AND ENGINEERING (BIG DATA ANALYTICS)"},
{key:"BM", label:"BIO MEDICAL ENGINEERING"},
{key:"BP", label:"B.Plan"},
{key:"BS", label:"BIO TECHNOLOGY (SS)"},
{key:"BT", label:"BIO TECHNOLOGY"},
{key:"BY", label:"BIO MEDICAL ENGINEERING (SS)"},
{key:"CA", label:"Computer Science and Engineering (Artificial Intelligence and Machine Learning)"},
{key:"CB", label:"COMPUTER SCIENCE AND BUSSINESS SYSTEM"},
{key:"CC", label:"CHEMICAL AND ELECTRO CHEMICAL ENGINEERING (SS)"},
{key:"CE", label:"CIVIL ENGINEERING"},
{key:"CG", label:"Computer Science and Engineering (Artificial Intelligence and Machine Learning) (SS)"},
{key:"CH", label:"CHEMICAL ENGINEERING"},
{key:"CI", label:"Computer Science and Engineering (Internet of Things)"},
{key:"CJ", label:"M.Tech. Computer Science and Engineering (Integrated 5 years)"},
{key:"CL", label:"CHEMICAL ENGINEERING (SS)"},
{key:"CM", label:"COMPUTER SCIENCE AND ENGINEERING (SS)"},
{key:"CN", label:"CIVIL ENGINEERING (SS)"},
{key:"CO", label:"COMPUTER AND COMMUNICATION ENGINEERING"},
{key:"CR", label:"CERAMIC TECHNOLOGY (SS)"},
{key:"CS", label:"COMPUTER SCIENCE AND ENGINEERING"},
{key:"CT", label:"COMPUTER TECHNOLOGY"},
{key:"CW", label:"Computer Science and Business System (SS)"},
{key:"CY", label:"Cyber Security"},
{key:"CZ", label:"CIVIL AND STRUCTUTURAL ENGINEERING"},
{key:"EC", label:"ELECTRONICS AND COMMUNICATION ENGINEERING"},
{key:"EE", label:"ELECTRICAL AND ELECTRONICS ENGINEERING"},
{key:"EI", label:"ELECTRONICS AND INSTRUMENTATION ENGINEERING"},
{key:"EM", label:"ELECTRONICS AND COMMUNICATION ENGINEERING (SS)"},
{key:"ES", label:"ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)"},
{key:"ET", label:"ELECTRONICS AND TELECOMMUNICATION ENGINEERING"},
{key:"EY", label:"ELECTRICAL AND ELECTRONICS ENGINEERING (SS)"},
{key:"FD", label:"FOOD TECHNOLOGY"},
{key:"FS", label:"FOOD TECHNOLOGY (SS)"},
{key:"FT", label:"FASHION TECHNOLOGY"},
{key:"FY", label:"FASHION TECHNOLOGY (SS)"},
{key:"GI", label:"GEO INFORMATICS"},
{key:"HT", label:"HANDLOOM AND TEXTILE TECHNOLOGY"},
{key:"IB", label:"INDUSTRIAL BIO TECHNOLOGY"},
{key:"IC", label:"INSTRUMENTATION AND CONTROL ENGINEERING"},
{key:"IE", label:"INDUSTRIAL ENGINEERING"},
{key:"IM", label:"INFORMATION TECHNOLOGY (SS)"},
{key:"IN", label:"INDUSTRIAL ENGINEERING AND MANAGEMENT"},
{key:"IS", label:"INDUSTRIAL BIO TECHNOLOGY (SS)"},
{key:"IT", label:"INFORMATION TECHNOLOGY"},
{key:"IY", label:"INSTRUMENTATION AND CONTROL ENGINEERING (SS)"},
{key:"LE", label:"LEATHER TECHNOLOGY"},
{key:"MA", label:"MATERIAL SCIENCE AND ENGINEERING (SS)"},
{key:"MC", label:"MECHATRONICS"},
{key:"MD", label:"MEDICAL ELECTRONICS ENGINEERING"},
{key:"ME", label:"MECHANICAL ENGINEERING"},
{key:"MF", label:"MECHANICAL ENGINEERING (SS)"},
{key:"MG", label:"MECHATRONICS (SS)"},
{key:"MH", label:"MECHANICAL ENGINEERING (SANDWICH)"},
{key:"MI", label:"MINING ENGINEERING"},
{key:"MM", label:"MECHANICAL ENGINEERING (MANUFACTURING)"},
{key:"MN", label:"MANUFACTURING ENGINEERING"},
{key:"MO", label:"Mechanical and Mechatronics Engineering (Additive Manufacturing)"},
{key:"MR", label:"MARINE ENGINEERING"},
{key:"MS", label:"MECHANICAL ENGINEERING (SANDWICH) (SS)"},
{key:"MT", label:"METALLURGICAL ENGINEERING"},
{key:"MU", label:"MECHANICAL AND AUTOMATION ENGINEERING"},
{key:"MY", label:"METALLURGICAL ENGINEERING (SS)"},
{key:"MZ", label:"Mechatronics Engineering"},
{key:"NS", label:"NANO SCIENCE AND TECHNOLOGY"},
{key:"PA", label:"PLASTIC TECHNOLOGY"},
{key:"PC", label:"PETRO CHEMICAL TECHNOLOGY"},
{key:"PD", label:"PETRO CHEMICAL ENGINEERING"},
{key:"PE", label:"PETROLEUM ENGINEERING"},
{key:"PH", label:"PHARMACEUTICAL TECHNOLOGY"},
{key:"PL", label:"POLYMER TECHNOLOGY"},
{key:"PM", label:"PHARMACEUTICAL TECHNOLOGY (SS)"},
{key:"PN", label:"PRODUCTION ENGINEERING (SS)"},
{key:"PP", label:"PETROLEUM ENGINEERING AND TECHNOLOGY (SS)"},
{key:"PR", label:"PRODUCTION ENGINEERING"},
{key:"PS", label:"PRODUCTION ENGINEERING (SANDWICH) (SS)"},
{key:"PT", label:"PRINTING TECHNOLOGY"},
{key:"RA", label:"ROBOTICS AND AUTOMATION (SS)"},
{key:"RM", label:"ROBOTICS AND AUTOMATION"},
{key:"RP", label:"RUBBER AND PLASTIC TECHNOLOGY"},
{key:"SB", label:"Computer Science and Engineering (Internet of Things and Cyber Security including Block Chain Technology)"},
{key:"SC", label:"Computer Science and Engineering (Cyber Security)"},
{key:"SE", label:"Information Science and Engineering"},
{key:"SF", label:"Safety and Fire Engineering"},
{key:"TC", label:"TEXTILE CHEMISTRY"},
{key:"TS", label:"Computer Science and Technology"},
{key:"TT", label:"TEXTILE TECHNOLOGY (SS)"},
{key:"TX", label:"TEXTILE TECHNOLOGY"},
{key:"XC", label:"CIVIL ENGINEERING (TAMIL MEDIUM)"},
{key:"XM", label:"MECHANICAL ENGINEERING (TAMIL MEDIUM)"},
{key:"AT", label:"ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)"},
{key:"CD", label:"COMPUTER SCIENCE AND DESIGN"},
{key:"CF", label:"COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)"},
{key:"EN", label:"ENVIRONMENTAL ENGINEERING"},
{key:"PU", label:"PHARMACEUTICAL ENGINEERING"},
{key:"XS", label:"COMPUTER SCIENCE AND ENGINEERING (TAMIL)"}

   ];

   module.exports = {DEPT_LIST,COLLEGES_LIST};